server:
  port: 8007


eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer1:8761/eureka

feign:
  name: eureka-client
  url: http://localhost:8002

spring.boot.admin.url: http://peer1:8005
management.security.enabled: false