server:
  port: 8005

zuul:
  ## 只允许eureka-client这个服务的访问, 如果去掉ignored-services, 默认是可以使用/serviceId, 和指定的/client访问的
  ignored-services: '*'
  routes:
    eureka-client:
      ## 细粒度路由控制
      path: /client/**
      serviceId: eureka-client
      ## 关闭前缀剥离, 默认为true, 如果开启效果为/client/contextPath, 如果关闭则为/contextPath
      strip-prefix: false

#    手工指定物理地址
#    eureka-client:
#      path: /client/**
#      url: http://boxfish.com/fishcard

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer1:8761/eureka