server:
  port: 8006

## eureka-client指定负载均衡算法为，响应时间加权算法
eureka-client:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    listOfServers: http://localhost:8002

ribbon:
  eureka:
    enabled: false

#eureka:
#  client:
#    service-url:
#      defaultZone: http://peer1:8761/eureka
