spring.profiles.active: peer1
---
server:
  port: 8761
spring.profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:${server.port}/eureka/
---
server:
  port: 8762
spring.profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
    ## ${eureka.instance.hostname}
      defaultZone: http://peer1:${server.port}/eureka
