server:
  port: 8888

encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme

#person:
#  name: luolibing
#  age: 30
#---
#spring.profiles: product
#person:
#  name: liuxiaoling
#  age: 30
#
#---
#spring.profiles: test
#person:
#  name: luominghao
#  age: 5